# Generated by Django 4.1.5 on 2026-03-14 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=20, verbose_name='Студенттік ID')),
                ('course', models.PositiveSmallIntegerField(default=3, verbose_name='Курс')),
                ('faculty', models.CharField(default='Ақпараттық технологиялар', max_length=100, verbose_name='Факультет')),
                ('specialty', models.CharField(default='Ақпараттық жүйелер', max_length=100, verbose_name='Мамандық')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Студент профилі',
                'verbose_name_plural': 'Студент профильдері',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тақырып')),
                ('message', models.TextField(verbose_name='Хабарлама')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Хабарлама',
                'verbose_name_plural': 'Хабарламалар',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Пән')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Баға')),
                ('exam_status', models.CharField(blank=True, max_length=50, verbose_name='Емтихан')),
                ('status', models.CharField(default='Өтті', max_length=20, verbose_name='Мәртебе')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Баға',
                'verbose_name_plural': 'Бағалар',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=100, verbose_name='Құжат түрі')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Қаралуда'), ('ready', 'Дайын')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Құжат',
                'verbose_name_plural': 'Құжаттар',
            },
        ),
    ]
