# Generated by Django 4.1.5 on 2026-03-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Дүйсенбі'), (2, 'Сейсенбі'), (3, 'Сәрсенбі'), (4, 'Бейсенбі'), (5, 'Жұма')])),
                ('time_start', models.TimeField(verbose_name='Басталу')),
                ('time_end', models.TimeField(verbose_name='Аяқталу')),
                ('subject', models.CharField(max_length=100, verbose_name='Пән')),
                ('course', models.PositiveSmallIntegerField(default=3, verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Кесте',
                'verbose_name_plural': 'Кестелер',
                'ordering': ['day', 'time_start'],
            },
        ),
    ]
