# Generated by Django 4.1.5 on 2026-03-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Қысқаша сипаттама', max_length=200, verbose_name='Тақырып / Мәселе')),
                ('keywords', models.CharField(blank=True, help_text='Студент сұрағанда ізделетін сөздер (мысалы: справка, құжат, кесте)', max_length=300, verbose_name='Кілт сөздер')),
                ('solution', models.TextField(help_text='Мәселені қалай шешу керек', verbose_name='Шешім / Жауап')),
                ('is_active', models.BooleanField(default=True, verbose_name='Белсенді')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Кіші сан — бірінші', verbose_name='Рет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Мәселе шешімі',
                'verbose_name_plural': 'Мәселе шешімдері',
                'ordering': ['order', 'topic'],
            },
        ),
    ]
